mqtt:
  client:
    protocol: 4 # MQTTv311
  account:
    username: "$(env VERNEMQ_USER)"
    password: "$(env VERNEMQ_PASSWORD)"
  connection:
    host: mqtt_broker
    port: 1883
    keepalive: 60
serializer: json:dumps
deserializer: json:loads
bridge:
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: nav_msgs.msg:Odometry
    topic_from: /chatter
    topic_to: chatter
